### ISSUE TITLE
[BUG] Crash due to missing '#' in Constants.java

### ISSUE THREAD

**Issue by RaghavAwasthi** [krharsh17/barview-android#28]
**Describe the bug**
The current version of the Android app is crashing on Launch

**To Reproduce**
1. Run the app on Android device
2. See the app crashing

**Expected behavior**
The app should show the current implementation of Bar View

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/24982437/75624227-89222000-5bd8-11ea-8924-c501159bbaad.jpg)

**Additional context**
The bug arose because several resources were not moved properly to the constants file. 
This bug was introduced in PR https://github.com/krharsh17/barview-android/pull/19

I would like to work on this issue

** Stack Trace**
```
Process: in.krharsh17.barview_sample, PID: 6933
    java.lang.IllegalArgumentException: Unknown color
        at android.graphics.Color.parseColor(Color.java:1400)
        at in.krharsh17.barview.BarGroup.setupInitial(BarGroup.java:112)
        at in.krharsh17.barview.BarGroup.onAttachedToWindow(BarGroup.java:81)
        at android.view.View.dispatchAttachedToWindow(View.java:19553)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2028)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by krharsh17** [comment]
Could you please share the stack trace here?

**Comment by RaghavAwasthi** [comment]
@krharsh17  I was able to fix it. The issue was with `Constants.java` file in that the colour resource was not preceded by '#'.

**Comment by krharsh17** [comment]
Alright. Good job!
